"use client";

import { Inter } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });
import { ChakraProvider } from "@chakra-ui/react";
import { ThemeProvider } from "@/Components/theme-provider";
import { SpeedInsights } from "@vercel/speed-insights/next";
import { Analytics } from "@vercel/analytics/react";
import Navbar from "@/Components/Navbar";
import "./globals.css";

// export const metadata = {
//     title: "Create Next App",
//     description: "Generated by create next app",----- // can't enable this becouse this create problem in nextUiProvider !!
// };

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <ChakraProvider>
                    <ThemeProvider
                        attribute="class"
                        defaultTheme="system"
                        enableSystem
                        disableTransitionOnChange>
                        <Navbar />
                        {children}
                        <SpeedInsights />
                        <Analytics />
                    </ThemeProvider>
                </ChakraProvider>
            </body>
        </html>
    );
}
